
import React from "react";
import "../styles/Disclaimer.css";
import disclaimerBg from "../assets/desclaimer.jpeg"; // image with doctor on LEFT

const Disclaimer = () => {
  return (
    <div className="disclaimer-page">

      {/* ===== HERO SECTION (FULL SCREEN) ===== */}
      <section
        className="disclaimer-hero"
        style={{ backgroundImage: `url(${disclaimerBg})` }}
      >
        <div className="disclaimer-overlay">
          <h1>Disclaimer</h1>
          <p>
            Please read this disclaimer carefully before using our website.
          </p>

          {/* Disclaimer Card */}
          <div className="disclaimer-card">
            <div className="disclaimer-item">
              <h3>Educational Purpose</h3>
              <p>
                This website is created for educational and awareness purposes only.
                The information provided here should not be considered medical advice.
              </p>
            </div>

            <div className="disclaimer-item">
              <h3>Not a Medical Diagnosis</h3>
              <p>
                The prediction results generated by this system are based on machine
                learning models and are not 100% accurate. They should not replace
                professional medical diagnosis.
              </p>
            </div>

            <div className="disclaimer-item">
              <h3>Consult a Doctor</h3>
              <p>
                Always consult a qualified healthcare professional for proper
                medical advice, diagnosis, and treatment.
              </p>
            </div>

            <div className="disclaimer-item">
              <h3>No Liability</h3>
              <p>
                The developers of this website are not responsible for any
                decisions made based on the results provided by this system.
              </p>
            </div>

            <div className="disclaimer-item">
              <h3>External Links</h3>
              <p>
                This website may contain links to external resources. We are not
                responsible for the content or accuracy of third-party websites.
              </p>
            </div>

            <p className="disclaimer-footer">
              By using this website, you agree to this disclaimer.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Disclaimer;


